export type IconName =
  | 'arrow-right-16'
  | 'asterisk'
  | 'check'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevrons-up-down'
  | 'circle-alert'
  | 'minus'
  | 'plus'
  | 'search'
  | 'times'
